'use strict';

export const PERMISSIONS = {
  USERS_READ: 'users:read',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  USERS_ASSIGN_ROLE: 'users:assign-role',
  CUSTOMERS_READ: 'customers:read',
  CUSTOMERS_CREATE: 'customers:create',
  CUSTOMERS_UPDATE: 'customers:update',
  CUSTOMERS_DELETE: 'customers:delete',
  SEDES_READ: 'sedes:read',
  SEDES_CREATE: 'sedes:create',
  SEDES_UPDATE: 'sedes:update',
  SEDES_DELETE: 'sedes:delete',
  OTS_READ: 'ot:read',
  OTS_CREATE: 'ot:create',
  OTS_UPDATE: 'ot:update',
  OTS_DELETE: 'ot:delete',
  REPORTS_READ: 'reports:read',
  REPORTS_CREATE: 'reports:create',
  REPORTS_UPDATE: 'reports:update',
  REPORTS_DELETE: 'reports:delete',
  REPORTS_PDF: 'reports:pdf',
  EQUIPMENT_READ: 'equipo:read',
  EQUIPMENT_CREATE: 'equipo:create',
  EQUIPMENT_UPDATE: 'equipo:update',
  EQUIPMENT_DELETE: 'equipo:delete',
  INVENTORY_READ: 'inventario:read',
  INVENTORY_CREATE: 'inventario:create',
  INVENTORY_UPDATE: 'inventario:update',
  INVENTORY_DELETE: 'inventario:delete',
  SPARE_PARTS_READ: 'repuestos:read',
  SPARE_PARTS_CREATE: 'repuestos:create',
  SPARE_PARTS_UPDATE: 'repuestos:update',
  SPARE_PARTS_DELETE: 'repuestos:delete',
  PROTOCOLS_READ: 'protocols:read',
  PROTOCOLS_CREATE: 'protocols:create',
  PROTOCOLS_UPDATE: 'protocols:update',
  PROTOCOLS_DELETE: 'protocols:delete',
  CRONOGRAMS_READ: 'cronograma:read',
  CRONOGRAMS_PDF: 'cronograma:pdf',
};

export const PERMISSION_VALUES = Object.values(PERMISSIONS);