import Joi from 'joi';

export const createRepuestosDto = Joi.object({
  tenantId: Joi.string().optional(),
  ClienteId: Joi.string().hex().length(24).optional().label('ClienteId'),
  nombre: Joi.string().required().label('nombre'),
  Cantidad: Joi.alternatives().try(Joi.string(), Joi.number()).required().label('Cantidad'),
  CantidadInstalacion: Joi.number().optional().label('CantidadInstalacion'),
  Currency: Joi.string().optional().label('Currency'),
  EquipoId: Joi.string().hex().length(24).required().label('EquipoId'),
  EstadoAnterior: Joi.string().optional().label('EstadoAnterior'),
  EstadoSolicitud: Joi.string().optional().label('EstadoSolicitud'),
  ExchangeRate: Joi.number().optional().label('ExchangeRate'),
  FechaInstalacion: Joi.date().optional().label('FechaInstalacion'),
  FechaSolicitud: Joi.date().optional().label('FechaSolicitud'),
  observacion: Joi.string().allow('').optional().label('observacion'),
  ObservacionInstalacion: Joi.string().optional().label('ObservacionInstalacion'),
  OrdenId: Joi.string().hex().length(24).required().label('OrdenId'),
  origenRepuesto: Joi.string().allow('').optional().label('origenRepuesto'),
  PrecioRepuesto: Joi.number().optional().label('PrecioRepuesto'),
  Prioridad: Joi.string().optional().label('Prioridad'),
  InventarioItemId: Joi.string().hex().length(24).optional().label('InventarioItemId'),
  ReporteInstalacionId: Joi.string().hex().length(24).optional().label('ReporteInstalacionId'),
  ReporteSolicitudId: Joi.string().hex().length(24).optional().label('ReporteSolicitudId'),
  ResponsableInstalacion: Joi.string().hex().length(24).optional().label('ResponsableInstalacion'),
  ResponsableSolicitud: Joi.string().hex().length(24).required().label('ResponsableSolicitud'),
  FrecuenciaDeCambio: Joi.number().optional().label('FrecuenciaDeCambio'),
  Fotos: Joi.array().items(Joi.string()).optional().label('Fotos'),
});
